name: Deploy to HF Space
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_GITHUB }}
        run: |
            git remote add space https://$HF_TOKEN@huggingface.co/spaces/nicknobu/pubmed-summary-demo || true
            git push -f space HEAD:main
